version: '3'

services:

  postgres:
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
      
  redis:
    image: redis:latest
    restart: always

  rails:
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis
    build: .
    env_file:
      - .env
    environment: &RAILS_ENV
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/1
    volumes:
      - ./data/rails/uploads:/app/public/uploads
      - ./:/app
    ports:
      - 3000:3000
